
// This file has been generated by the GUI designer. Do not modify.
namespace YoutubeDLGui
{
	public partial class HelpDialog
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.TextView TextView;
		
		private global::Gtk.Label DialogTitle;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget YoutubeDLGui.HelpDialog
			this.Name = "YoutubeDLGui.HelpDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Help");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child YoutubeDLGui.HelpDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame1.LabelXalign = 0.5F;
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.TextView = new global::Gtk.TextView ();
			this.TextView.Buffer.Text = "\nTo use, simply past the URL of a YouTube video into the URL box and click Download. Feel free to expand the options and customize your download.\n\nComing soon:\n\t- Playlist support.\n\t- More options.";
			this.TextView.Name = "TextView";
			this.TextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkAlignment1.Add (this.TextView);
			this.frame1.Add (this.GtkAlignment1);
			this.DialogTitle = new global::Gtk.Label ();
			this.DialogTitle.Name = "DialogTitle";
			this.DialogTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Help</b>");
			this.DialogTitle.UseMarkup = true;
			this.frame1.LabelWidget = this.DialogTitle;
			w1.Add (this.frame1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.frame1]));
			w4.Position = 0;
			// Internal child YoutubeDLGui.HelpDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
