
// This file has been generated by the GUI designer. Do not modify.
namespace YoutubeDLGui
{
	public sealed partial class MainWindow
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;

	    private void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget YoutubeDLGui.MainWindow
			this.Name = "YoutubeDLGui.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("YoutubeDL");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child YoutubeDLGui.MainWindow.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (OnDeleteEvent);
		}
	}
}
