
// This file has been generated by the GUI designer. Do not modify.
namespace YoutubeDLGui
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.TextView textview4;
		
		private global::Gtk.Label GtkLabel;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.CheckButton checkbutton8;
		
		private global::Gtk.CheckButton checkbutton9;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.CheckButton proxyCheckButton;
		
		private global::Gtk.TextView proxyUrlTextView;
		
		private global::Gtk.CheckButton socketTimeoutCheckButton;
		
		private global::Gtk.TextView socketTimeoutTextView;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.CheckButton rateLimitCheckButton;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.TextView rateTextView;
		
		private global::Gtk.ComboBox rateUnitComboBox;
		
		private global::Gtk.CheckButton retriesCheckButton;
		
		private global::Gtk.TextView retriesTextView;
		
		private global::Gtk.Label GtkLabel10;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.CheckButton overwritesCheckButton;
		
		private global::Gtk.RadioButton defaultContinueRadioButton;
		
		private global::Gtk.RadioButton continueRadioButton;
		
		private global::Gtk.RadioButton noContinueRadioButton;
		
		private global::Gtk.Label GtkLabel14;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.TextView usernameTextView;
		
		private global::Gtk.TextView passwordTextView;
		
		private global::Gtk.CheckButton passwordCheckButton;
		
		private global::Gtk.TextView twoFactorTextView;
		
		private global::Gtk.TextView videoPasswordTextView;
		
		private global::Gtk.CheckButton videoPasswordCheckButton;
		
		private global::Gtk.Label GtkLabel15;
		
		private global::Gtk.Button button16;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget YoutubeDLGui.MainWindow
			this.Name = "YoutubeDLGui.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("YoutubeDL");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child YoutubeDLGui.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame3.LabelXalign = 0.5F;
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.textview4 = new global::Gtk.TextView ();
			this.textview4.CanFocus = true;
			this.textview4.Name = "textview4";
			this.textview4.AcceptsTab = false;
			this.textview4.PixelsAboveLines = 2;
			this.textview4.PixelsBelowLines = 2;
			this.GtkAlignment.Add (this.textview4);
			this.frame3.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Youtube Video URL</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel;
			this.vbox1.Add (this.frame3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.checkbutton8 = new global::Gtk.CheckButton ();
			this.checkbutton8.CanFocus = true;
			this.checkbutton8.Name = "checkbutton8";
			this.checkbutton8.Label = global::Mono.Unix.Catalog.GetString ("Abort on error");
			this.checkbutton8.DrawIndicator = true;
			this.checkbutton8.UseUnderline = true;
			this.vbox7.Add (this.checkbutton8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.checkbutton8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.checkbutton9 = new global::Gtk.CheckButton ();
			this.checkbutton9.CanFocus = true;
			this.checkbutton9.Name = "checkbutton9";
			this.checkbutton9.Label = global::Mono.Unix.Catalog.GetString ("Ignore config");
			this.checkbutton9.DrawIndicator = true;
			this.checkbutton9.UseUnderline = true;
			this.vbox7.Add (this.checkbutton9);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.checkbutton9]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.GtkAlignment1.Add (this.vbox7);
			this.frame5.Add (this.GtkAlignment1);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>General Options</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel4;
			this.hbox2.Add (this.frame5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame5]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.proxyCheckButton = new global::Gtk.CheckButton ();
			this.proxyCheckButton.CanFocus = true;
			this.proxyCheckButton.Name = "proxyCheckButton";
			this.proxyCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Use Proxy");
			this.proxyCheckButton.DrawIndicator = true;
			this.proxyCheckButton.UseUnderline = true;
			this.vbox11.Add (this.proxyCheckButton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.proxyCheckButton]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.proxyUrlTextView = new global::Gtk.TextView ();
			this.proxyUrlTextView.Sensitive = false;
			this.proxyUrlTextView.CanFocus = true;
			this.proxyUrlTextView.Name = "proxyUrlTextView";
			this.vbox11.Add (this.proxyUrlTextView);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.proxyUrlTextView]));
			w10.Position = 1;
			// Container child vbox11.Gtk.Box+BoxChild
			this.socketTimeoutCheckButton = new global::Gtk.CheckButton ();
			this.socketTimeoutCheckButton.CanFocus = true;
			this.socketTimeoutCheckButton.Name = "socketTimeoutCheckButton";
			this.socketTimeoutCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enable socket timeout");
			this.socketTimeoutCheckButton.DrawIndicator = true;
			this.socketTimeoutCheckButton.UseUnderline = true;
			this.vbox11.Add (this.socketTimeoutCheckButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.socketTimeoutCheckButton]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.socketTimeoutTextView = new global::Gtk.TextView ();
			this.socketTimeoutTextView.Sensitive = false;
			this.socketTimeoutTextView.CanFocus = true;
			this.socketTimeoutTextView.Name = "socketTimeoutTextView";
			this.vbox11.Add (this.socketTimeoutTextView);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.socketTimeoutTextView]));
			w12.Position = 3;
			this.GtkAlignment2.Add (this.vbox11);
			this.frame6.Add (this.GtkAlignment2);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Network Options</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel7;
			this.hbox2.Add (this.frame6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame6]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w16.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.rateLimitCheckButton = new global::Gtk.CheckButton ();
			this.rateLimitCheckButton.CanFocus = true;
			this.rateLimitCheckButton.Name = "rateLimitCheckButton";
			this.rateLimitCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Limit download rate");
			this.rateLimitCheckButton.DrawIndicator = true;
			this.rateLimitCheckButton.UseUnderline = true;
			this.vbox2.Add (this.rateLimitCheckButton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.rateLimitCheckButton]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.rateTextView = new global::Gtk.TextView ();
			this.rateTextView.Sensitive = false;
			this.rateTextView.CanFocus = true;
			this.rateTextView.Name = "rateTextView";
			this.rateTextView.AcceptsTab = false;
			this.hbox1.Add (this.rateTextView);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rateTextView]));
			w18.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.rateUnitComboBox = global::Gtk.ComboBox.NewText ();
			this.rateUnitComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("K"));
			this.rateUnitComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("M"));
			this.rateUnitComboBox.Sensitive = false;
			this.rateUnitComboBox.Name = "rateUnitComboBox";
			this.hbox1.Add (this.rateUnitComboBox);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rateUnitComboBox]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.retriesCheckButton = new global::Gtk.CheckButton ();
			this.retriesCheckButton.CanFocus = true;
			this.retriesCheckButton.Name = "retriesCheckButton";
			this.retriesCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Limit number of retries");
			this.retriesCheckButton.DrawIndicator = true;
			this.retriesCheckButton.UseUnderline = true;
			this.vbox2.Add (this.retriesCheckButton);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.retriesCheckButton]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.retriesTextView = new global::Gtk.TextView ();
			this.retriesTextView.Sensitive = false;
			this.retriesTextView.CanFocus = true;
			this.retriesTextView.Name = "retriesTextView";
			this.retriesTextView.AcceptsTab = false;
			this.vbox2.Add (this.retriesTextView);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.retriesTextView]));
			w22.Position = 3;
			this.GtkAlignment3.Add (this.vbox2);
			this.frame1.Add (this.GtkAlignment3);
			this.GtkLabel10 = new global::Gtk.Label ();
			this.GtkLabel10.Name = "GtkLabel10";
			this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Download Options</b>");
			this.GtkLabel10.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel10;
			this.hbox4.Add (this.frame1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame1]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.overwritesCheckButton = new global::Gtk.CheckButton ();
			this.overwritesCheckButton.CanFocus = true;
			this.overwritesCheckButton.Name = "overwritesCheckButton";
			this.overwritesCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Do not overwrite file");
			this.overwritesCheckButton.DrawIndicator = true;
			this.overwritesCheckButton.UseUnderline = true;
			this.vbox3.Add (this.overwritesCheckButton);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.overwritesCheckButton]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.defaultContinueRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Resume downloads of partially downloaded files if possible"));
			this.defaultContinueRadioButton.CanFocus = true;
			this.defaultContinueRadioButton.Name = "defaultContinueRadioButton";
			this.defaultContinueRadioButton.DrawIndicator = true;
			this.defaultContinueRadioButton.UseUnderline = true;
			this.defaultContinueRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox3.Add (this.defaultContinueRadioButton);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.defaultContinueRadioButton]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.continueRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Force partially downloaded files to resume"));
			this.continueRadioButton.CanFocus = true;
			this.continueRadioButton.Name = "continueRadioButton";
			this.continueRadioButton.DrawIndicator = true;
			this.continueRadioButton.UseUnderline = true;
			this.continueRadioButton.Group = this.defaultContinueRadioButton.Group;
			this.vbox3.Add (this.continueRadioButton);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.continueRadioButton]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.noContinueRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Do not resume partially downloaded files"));
			this.noContinueRadioButton.CanFocus = true;
			this.noContinueRadioButton.Name = "noContinueRadioButton";
			this.noContinueRadioButton.DrawIndicator = true;
			this.noContinueRadioButton.UseUnderline = true;
			this.noContinueRadioButton.Group = this.defaultContinueRadioButton.Group;
			this.vbox3.Add (this.noContinueRadioButton);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.noContinueRadioButton]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			this.GtkAlignment4.Add (this.vbox3);
			this.frame2.Add (this.GtkAlignment4);
			this.GtkLabel14 = new global::Gtk.Label ();
			this.GtkLabel14.Name = "GtkLabel14";
			this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Filesystem Options</b>");
			this.GtkLabel14.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel14;
			this.hbox4.Add (this.frame2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame2]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.usernameTextView = new global::Gtk.TextView ();
			this.usernameTextView.Buffer.Text = "Username";
			this.usernameTextView.CanFocus = true;
			this.usernameTextView.Name = "usernameTextView";
			this.usernameTextView.AcceptsTab = false;
			this.vbox4.Add (this.usernameTextView);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.usernameTextView]));
			w34.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.passwordTextView = new global::Gtk.TextView ();
			this.passwordTextView.Buffer.Text = "Password";
			this.passwordTextView.CanFocus = true;
			this.passwordTextView.Name = "passwordTextView";
			this.passwordTextView.AcceptsTab = false;
			this.vbox4.Add (this.passwordTextView);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.passwordTextView]));
			w35.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.passwordCheckButton = new global::Gtk.CheckButton ();
			this.passwordCheckButton.CanFocus = true;
			this.passwordCheckButton.Name = "passwordCheckButton";
			this.passwordCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Show account password");
			this.passwordCheckButton.DrawIndicator = true;
			this.passwordCheckButton.UseUnderline = true;
			this.vbox4.Add (this.passwordCheckButton);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.passwordCheckButton]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.twoFactorTextView = new global::Gtk.TextView ();
			this.twoFactorTextView.Buffer.Text = "Two-factor auth code";
			this.twoFactorTextView.CanFocus = true;
			this.twoFactorTextView.Name = "twoFactorTextView";
			this.twoFactorTextView.AcceptsTab = false;
			this.vbox4.Add (this.twoFactorTextView);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.twoFactorTextView]));
			w37.Position = 3;
			// Container child vbox4.Gtk.Box+BoxChild
			this.videoPasswordTextView = new global::Gtk.TextView ();
			this.videoPasswordTextView.Buffer.Text = "Video password";
			this.videoPasswordTextView.CanFocus = true;
			this.videoPasswordTextView.Name = "videoPasswordTextView";
			this.videoPasswordTextView.AcceptsTab = false;
			this.vbox4.Add (this.videoPasswordTextView);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.videoPasswordTextView]));
			w38.Position = 4;
			// Container child vbox4.Gtk.Box+BoxChild
			this.videoPasswordCheckButton = new global::Gtk.CheckButton ();
			this.videoPasswordCheckButton.CanFocus = true;
			this.videoPasswordCheckButton.Name = "videoPasswordCheckButton";
			this.videoPasswordCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Show video password");
			this.videoPasswordCheckButton.DrawIndicator = true;
			this.videoPasswordCheckButton.UseUnderline = true;
			this.vbox4.Add (this.videoPasswordCheckButton);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.videoPasswordCheckButton]));
			w39.Position = 5;
			w39.Expand = false;
			w39.Fill = false;
			this.GtkAlignment5.Add (this.vbox4);
			this.frame4.Add (this.GtkAlignment5);
			this.GtkLabel15 = new global::Gtk.Label ();
			this.GtkLabel15.Name = "GtkLabel15";
			this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Authentication Options</b>");
			this.GtkLabel15.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel15;
			this.hbox3.Add (this.frame4);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame4]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w43.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.button16 = new global::Gtk.Button ();
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			this.button16.Label = global::Mono.Unix.Catalog.GetString ("Download");
			this.vbox1.Add (this.button16);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button16]));
			w44.PackType = ((global::Gtk.PackType)(1));
			w44.Position = 4;
			w44.Expand = false;
			w44.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 814;
			this.DefaultHeight = 620;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.proxyCheckButton.Toggled += new global::System.EventHandler (this.OnProxyCheckButtonToggled);
			this.socketTimeoutCheckButton.Toggled += new global::System.EventHandler (this.OnSocketTimeoutCheckButtonToggled);
			this.rateLimitCheckButton.Toggled += new global::System.EventHandler (this.OnRateLimitCheckButtonToggled);
			this.retriesCheckButton.Toggled += new global::System.EventHandler (this.OnRetriesCheckButtonToggled);
			this.usernameTextView.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnUsernameTextViewKeyReleaseEvent);
			this.usernameTextView.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnUsernameTextViewFocusOutEvent);
			this.passwordTextView.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnPasswordTextViewKeyReleaseEvent);
			this.passwordTextView.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnPasswordTextViewFocusOutEvent);
			this.passwordCheckButton.Toggled += new global::System.EventHandler (this.OnPasswordCheckButtonToggled);
			this.videoPasswordTextView.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnVideoPasswordTextViewKeyReleaseEvent);
		}
	}
}
